# -*- coding: utf-8 -*-
"""SQL Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jEGKTr9tHbQHsNN45kzhwnmgVNqEGnjn
"""

pip install -U transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct"
)

messages = [
    {"role": "user", "content": "Who are you?"},
]

pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")

messages = [
    {"role": "user", "content": "Who are you?"}
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_tensors="pt",
    return_dict=True
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=50)

print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

!pip install -q gradio transformers torch black autopep8 reportlab requests

!pip install -q gradio transformers torch black autopep8 reportlab requests sqlite3

import gradio as gr
from datetime import datetime
from pathlib import Path
import json
import sqlite3
import re
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
import requests
import urllib.parse
# ==================================================
# DATABASE SCHEMA
# ==================================================

SCHEMA = {
    "users": {
        "id": "INTEGER PRIMARY KEY",
        "name": "TEXT",
        "email": "TEXT",
        "signup_date": "DATE",
        "age": "INTEGER",
        "country": "TEXT",
        "status": "TEXT"
    },
'orders': {
    'id': 'INTEGER PRIMARY KEY',
    'user_id': 'INTEGER',
    'product_name': 'TEXT',
    'amount': 'REAL',
    'order_date': 'DATE',
    'status': 'TEXT'
},

'products': {
    'id': 'INTEGER PRIMARY KEY',
    'name': 'TEXT',
    'price': 'REAL',
    'category': 'TEXT',
    'stock': 'INTEGER'
},

'transactions': {
    'id': 'INTEGER PRIMARY KEY',
    'user_id': 'INTEGER',
    'amount': 'REAL',
    'date': 'DATE',
    'type':'TEXT'
}
}

# ===============================
# SECURITY & SQL GENERATION
# ===============================

DANGEROUS_KEYWORDS = [
    'DROP', 'DELETE', 'ALTER', 'TRUNCATE',
    'INSERT', 'UPDATE', 'EXEC', 'EXECUTE'
]

DANGEROUS_CHARS = [
    "'", '"', ';', '--', '/', '/', 'xp_', 'sp_'
]

def is_safe(text):
    """Check if text contains dangerous SQL keywords"""
    text_upper = text.upper()

    for keyword in DANGEROUS_KEYWORDS:
        if keyword in text_upper:
            return False

    for char in DANGEROUS_CHARS:
        if char in text:
            return False

    return True
def get_table_name(query_text):
    """Intelligently infer table name from natural language"""

    query_lower = query_text.lower()

    keyword_map = {
        'users': [
            'user', 'users', 'customer', 'customers',
            'account', 'accounts', 'profile'
        ],

        'orders': [
            'order', 'orders', 'purchase', 'purchases',
            'buy', 'bought'
        ],

        'products': [
            'product', 'products', 'item', 'items',
            'goods'
        ],

        'transactions': [
            'transaction', 'transactions', 'payment',
            'payments', 'transfer'
        ]
    }
    for table, keywords in keyword_map.items():
        for keyword in keywords:
            if keyword in query_lower:
                return table
    return None # Added to handle cases where no table is found

def get_column_names(table, query_text):
    """Extract column names from natural language query based on schema"""

    query_lower = query_text.lower()
    selected_cols = []
    table_schema = SCHEMA.get(table, {})

    for col in table_schema.keys():
        if col.lower() in query_lower:
            selected_cols.append(col)

    if not selected_cols:
        selected_cols = ['*']
    else:
        selected_cols = list(dict.fromkeys(selected_cols))  # Remove duplicates

    return selected_cols


def extract_conditions(query_text):
    """Extract WHERE conditions from natural language"""

    query_lower = query_text.lower()
    conditions = []

    # Last month
    if 'last month' in query_lower:
        conditions.append("DATE(signup_date) >= DATE('now', '-1 month')")
    # Last year
    if 'last year' in query_lower or 'this year' in query_lower:
        conditions.append("DATE(signup_date) >= DATE('now', '-1 year')")

# Specific date patterns
    if 'last week' in query_lower:
        conditions.append("DATE(signup_date) >= DATE('now', '-7 days')")

    if 'today' in query_lower:
        conditions.append("DATE(signup_date) = DATE('now')")

# Active/inactive
    if 'active' in query_lower:
        conditions.append("status = 'active'")
    elif 'inactive' in query_lower:
        conditions.append("status = 'inactive'")

# Amount filtering
    amount_match = re.search(r"(more than|greater than|above)\s+([0-9]+)", query_lower)
    if amount_match:
        conditions.append(f"amount > {amount_match.group(2)}") # Changed group(1) to group(2) to get the number

    amount_match = re.search(r'(less than|below)\s+([0-9]+)', query_lower)
    if amount_match:
        conditions.append(f"amount < {amount_match.group(2)}") # Changed group(1) to group(2) to get the number

    return conditions


def generate_sql(query_text):
    """Generate SQLite SQL from natural language"""

    if not is_safe(query_text):
        return None, "❌ UNSAFE: Query contains dangerous SQL keywords!"
    table = get_table_name(query_text)
    if not table:
        return None, "❌ ERROR: Could not determine table name from query."
    columns = get_column_names(table, query_text)

    columns_str = ', '.join(columns) if columns != [''] else '*'

    # Build base query
    sql = f"SELECT {columns_str} FROM {table}"

    # Add conditions
    conditions = extract_conditions(query_text)
    if conditions:
        sql += " WHERE " + " AND ".join(conditions)

    # Add limit
    if "all" not in query_text.lower():
        sql += " LIMIT 10"

    return sql, f"🟩 Generated from table '{table}' with columns {columns_str}"

query_history = []

def process_query(user_query, chat_history):
    """Process database query request"""

    if not user_query.strip():
        return chat_history

    chat_history.append((user_query, "Processing..."))

    sql_query, explanation = generate_sql(user_query)

    if sql_query is None:
        response = f"❌ ERROR:\n{explanation}"
    else:
        response = f"⬜ SQL GENERATED:\n\n```sql\n{sql_query}\n```\n\n🧠 {explanation}"

    query_history.append({
        "user": user_query,
        "sql": sql_query,
        "timestamp": datetime.now().isoformat()
    })
    chat_history[-1] = (user_query, response)
    return chat_history

def clear_chat(): # Added colon
    global query_history
    query_history = [] # Clears the history
    return [] # Clear the chatbot display

def generate_pdf(): # Moved PDF generation into its own function
    if not query_history:
        return "❌ No queries to export!", None

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"sql_quiz_{timestamp}.pdf"

    try:
        doc = SimpleDocTemplate(filename, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=20,
            textColor=colors.red, # Fixed color definition
            spaceAfter=30,
            alignment=1
        )

        story.append(Paragraph("🔥 SQL Quiz Report", title_style))
        story.append(Paragraph(f"Generated on: {datetime.now()}", styles["Normal"]))

        for i, query in enumerate(query_history, 1):
            story.append(Paragraph(f"<b>Query {i}</b>", styles['Heading2']))
            story.append(Paragraph(f"<b>User Request:</b> {query['user']}", styles['Normal']))
            story.append(Paragraph(f"<b>Generated SQL:</b> <font face='Courier'> {query['sql']}</font>", styles['Normal']))
            story.append(Paragraph(f"<b>Timestamp:</b> {query['timestamp']}", styles['Normal']))
            story.append(Spacer(1, 0.2 * inch))

        doc.build(story)
        return f"✅ PDF Generated: {filename}", filename
    except Exception as e:
        return f"❌ Error generating PDF: {str(e)}", None

def download_txt():
    if not query_history:
        return "❌ No queries to export!", None

    content = f"SQL Query History Report\nGenerated: {datetime.now()}\n\n"

    for i, query in enumerate(query_history, 1):
        content += f"Query #{i}:\n"
        content += f"User Request: {query['user']}\n"
        content += f"Generated SQL: {query['sql']}\n"
        content += f"Timestamp: {query['timestamp']}\n"
        content += f"{'-'*60}\n\n"

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"sql_queries_{timestamp}.txt"

    return content, filename

def create_whatsapp_link(): # Renamed from generate_whatsapp_link for consistency with usage
    if not query_history:
        return "❌ No Queries to Share"

    message = "SQL Queries Generated\n\n"
    for i, query in enumerate(query_history[-5:], 1):
        message += f"{i}. User Request: {query['user']}\n"
        message += f"    Generated SQL: {query['sql']}\n\n"

    encoded_message = urllib.parse.quote(message)
    whatsapp_link = f"https://wa.me/?text={encoded_message}"

    return f"📱 WhatsApp Link Created!\n\n🔗 {whatsapp_link}\n\n📌 Click to open WhatsApp and share!"

def generate_facebook_link(): # Placeholder for Facebook link generation
    return "Facebook sharing is not yet implemented."


# Gradio Interface
with gr.Blocks() as demo:
    gr.Markdown("## SQL Query Generator")
    gr.Markdown("Convert plain English requests into safe, production-ready SQL queries!")

    with gr.Row():
        with gr.Column(scale=3):
            chatbot = gr.Chatbot(
                label="🧠 Query Conversation",
                height=450,
                show_copy_button=True,
                bubble_full_width=False
            )

    with gr.Row():
        query_input = gr.Textbox(
            label="📝 Natural Language Request",
            placeholder="e.g. Show me all users who signed up last month",
            lines=2,
            scale=4
        )
        send_btn = gr.Button("Generate SQL", scale=1, size="lg", variant="primary")

    send_btn.click(
        process_query,
        inputs=[query_input, chatbot],
        outputs=chatbot
    )

    query_input.submit(
        process_query,
        inputs=[query_input, chatbot],
        outputs=chatbot
    )

    with gr.Column(scale=1):
        gr.Markdown("### Controls")

        clear_btn = gr.Button("🗑 Clear History", variant="stop", size="sm")
        clear_btn.click(clear_chat, outputs=chatbot) # Modified outputs to clear chatbotgr.Markdown("--- Polarization")
        gr.Markdown("### Export")

        pdf_btn = gr.Button("📄 Download PDF", size="sm", variant="secondary")
        txt_btn = gr.Button("📝 Download TXT", size="sm", variant="secondary")

        pdf_btn.click(generate_pdf, outputs=[gr.Textbox(label="PDF Status", interactive=False), gr.File(label="Download PDF")])
        txt_btn.click(download_txt, outputs=[gr.Textbox(label="TXT Content", interactive=False), gr.File(label="Download TXT")])

        gr.Markdown("### 🔗 Share")

        whatsapp_btn = gr.Button("💬 WhatsApp", size="sm", variant="secondary")
        facebook_btn = gr.Button("👍 Facebook", size="sm", variant="secondary")

        share_output = gr.Textbox(label="Share Link", interactive=False, lines=5)

        whatsapp_btn.click(create_whatsapp_link, outputs=share_output)
        facebook_btn.click(generate_facebook_link, outputs=share_output)

        gr.Markdown("--- Polarization")
        gr.Markdown("## 📊 Sales Info")

        gr.Markdown("### Supported Requests:")
        gr.Markdown("- List queries (e.g., users who signed up last month, products in stock)")
        gr.Markdown("- Filter by conditions (e.g., active users, orders more than $100)")

if __name__ == "__main__":
    demo.launch(share=True, show_error=True, show_api=False)